import { type BaseErrorProps } from "src/shared/types/base_error_props";

export enum InvariantErrorCode {
  INVALID_EMAIL_FORMAT = "INVALID_EMAIL_FORMAT",
  INVALID_PASSWORD_FORMAT = "INVALID_PASSWORD_FORMAT",
  ROTATION_NOT_PERMITTED = "ROTATION_NOT_PERMITTED",
  REVOCATION_NOT_PERMITTED = "REVOCATION_NOT_PERMITTED",
  ROLE_ASSIGNMENT_FAILED = "ROLE_ASSIGNMENT_FAILED",
  BOOKING_MINIMUM_SEATS = "BOOKING_MINIMUM_SEATS",
  BOOKING_ALREADY_TERMINAL = "BOOKING_ALREADY_TERMINAL",
  BOOKING_CANNOT_EXPIRE = "BOOKING_CANNOT_EXPIRE",
  INVALID_BOOKING_TRANSITION = "INVALID_BOOKING_TRANSITION",
  PAYMENT_NOT_INITIATED = "PAYMENT_NOT_INITIATED",
  TICKET_GENERATION_NOT_ALLOWED = "TICKET_GENERATION_NOT_ALLOWED",
  TICKET_ALREADY_GENERATED = "TICKET_ALREADY_GENERATED",
  SEAT_NOT_AVAILABLE = "SEAT_NOT_AVAILABLE",
  INVALID_SEAT_TRANSITION = "INVALID_SEAT_TRANSITION",
  SEAT_NOT_HELD_BY_BOOKING = "SEAT_NOT_HELD_BY_BOOKING",
  SEAT_INVENTORY_EMPTY = "SEAT_INVENTORY_EMPTY",
  TICKET_ALREADY_USED = "TICKET_ALREADY_USED",
  TICKET_INVALID_STATUS = "TICKET_INVALID_STATUS",
  BOOKING_NOT_CONFIRMED = "BOOKING_NOT_CONFIRMED",
  BOOKING_ALREADY_CHECKED_IN = "BOOKING_ALREADY_CHECKED_IN",
}

export class InvariantError extends Error {
  public readonly code: InvariantErrorCode;

  constructor(props: BaseErrorProps<InvariantError>) {
    super(props.message);
    this.code = props.code;
    this.name = this.constructor.name;
  }
}
